export const F1 = "f1"
export const F2 = "f2"
export const F3 = "f3"

export const NUM_LOCK = "numpad_lock"
export const ITEM_TOP_LEFT = "numpad_7"
export const ITEM_MIDDLE_LEFT = "numpad_4"
export const ITEM_BOTTOM_LEFT = "numpad_1"
export const ITEM_TOP_RIGHT = "numpad_8"
export const ITEM_MIDDLE_RIGHT = "numpad_5"
export const ITEM_BOTTOM_RIGHT = "numpad_2"
